window.EcoBalconPlants = [
  {
    name: "Basilic",
    exposure: ["soleil", "mi-ombre"],
    wind: ["abrite", "modere"],
    space: ["petit", "moyen", "grand"],
    goals: ["aromatiques", "facile"],
    potLiters: 5,
    waterNeed: 4,
    compostNeed: 2,
    difficulty: "Facile",
    harvest: "Feuilles de juin à octobre",
    tags: ["Aromatique", "Facile", "Pot"],
    description: "Une valeur sûre sur balcon si vous avez de la lumière et des arrosages réguliers.",
    tips: ["Arrosez dès que la surface sèche", "Pincez les tiges pour le faire ramifier"]
  },
  {
    name: "Tomate cerise",
    exposure: ["soleil"],
    wind: ["abrite", "modere"],
    space: ["moyen", "grand"],
    goals: ["legumes"],
    potLiters: 25,
    waterNeed: 5,
    compostNeed: 4,
    difficulty: "Moyen",
    harvest: "Récoltes d'été sur balcon chaud",
    tags: ["Légume", "Productif", "Soleil"],
    description: "Très intéressante en balcon ensoleillé avec un pot profond et un tuteur.",
    tips: ["Utilisez un grand pot", "Arrosez régulièrement sans détremper"]
  },
  {
    name: "Fraisier",
    exposure: ["soleil", "mi-ombre"],
    wind: ["abrite", "modere"],
    space: ["petit", "moyen", "grand"],
    goals: ["legumes", "facile"],
    potLiters: 4,
    waterNeed: 3,
    compostNeed: 3,
    difficulty: "Facile",
    harvest: "Fruits selon variété, printemps à été",
    tags: ["Fruit", "Petit espace", "Accessible"],
    description: "Un classique facile à placer en jardinière ou en suspension.",
    tips: ["Retirez les feuilles abîmées", "Apportez un peu d'engrais en saison"]
  },
  {
    name: "Radis",
    exposure: ["soleil", "mi-ombre"],
    wind: ["abrite", "modere", "fort"],
    space: ["petit", "moyen", "grand"],
    goals: ["legumes", "facile"],
    potLiters: 3,
    waterNeed: 3,
    compostNeed: 1,
    difficulty: "Très facile",
    harvest: "Récolte rapide en 3 à 6 semaines",
    tags: ["Légume", "Rapide", "Débutant"],
    description: "Pratique pour débuter : pousse vite et demande peu de place.",
    tips: ["Semez peu mais souvent", "Éclaircissez si les semis sont serrés"]
  },
  {
    name: "Laitue à couper",
    exposure: ["mi-ombre", "soleil"],
    wind: ["abrite", "modere"],
    space: ["petit", "moyen", "grand"],
    goals: ["legumes", "facile"],
    potLiters: 4,
    waterNeed: 4,
    compostNeed: 2,
    difficulty: "Facile",
    harvest: "Feuilles régulières hors grosses chaleurs",
    tags: ["Légume", "Petit espace", "Simple"],
    description: "Très bien pour récolter au fil des besoins sans gros matériel.",
    tips: ["Évitez les fortes chaleurs sans arrosage", "Récoltez feuille par feuille"]
  },
  {
    name: "Poivron",
    exposure: ["soleil"],
    wind: ["abrite", "modere"],
    space: ["moyen", "grand"],
    goals: ["legumes"],
    potLiters: 18,
    waterNeed: 4,
    compostNeed: 4,
    difficulty: "Moyen",
    harvest: "Fruits en été sur balcon chaud",
    tags: ["Légume", "Soleil", "Pot profond"],
    description: "Un bon choix sur balcon chaud et lumineux, avec un contenant stable et profond.",
    tips: ["Prévoyez un pot assez grand", "Maintenez une humidité régulière en été"]
  },
  {
    name: "Menthe",
    exposure: ["mi-ombre", "ombre"],
    wind: ["abrite", "modere"],
    space: ["petit", "moyen", "grand"],
    goals: ["aromatiques", "facile"],
    potLiters: 5,
    waterNeed: 4,
    compostNeed: 2,
    difficulty: "Très facile",
    harvest: "Feuilles pendant toute la belle saison",
    tags: ["Aromatique", "Tolère l'ombre", "Vigoureuse"],
    description: "Très simple à cultiver, idéale pour un balcon moins ensoleillé.",
    tips: ["Gardez-la en pot séparé", "Arrosez régulièrement en été"]
  },
  {
    name: "Thym",
    exposure: ["soleil"],
    wind: ["abrite", "modere", "fort"],
    space: ["petit", "moyen", "grand"],
    goals: ["aromatiques", "facile"],
    potLiters: 3,
    waterNeed: 1,
    compostNeed: 1,
    difficulty: "Très facile",
    harvest: "Tiges parfumées presque toute l'année",
    tags: ["Aromatique", "Soleil", "Peu d'eau"],
    description: "Une aromatique sobre et très adaptée aux balcons lumineux et bien drainés.",
    tips: ["Arrosez avec modération", "Taillez légèrement après la floraison"]
  },
  {
    name: "Lavande",
    exposure: ["soleil"],
    wind: ["abrite", "modere", "fort"],
    space: ["moyen", "grand"],
    goals: ["fleurs", "facile", "aromatiques"],
    potLiters: 10,
    waterNeed: 1,
    compostNeed: 1,
    difficulty: "Facile",
    harvest: "Floraison parfumée et mellifère",
    tags: ["Méditerranéenne", "Soleil", "Peu d'eau"],
    description: "Excellente en plein soleil, surtout sur balcon chaud et bien drainé.",
    tips: ["Choisissez un substrat drainant", "Arrosez sans excès"]
  },
  {
    name: "Capucine",
    exposure: ["soleil", "mi-ombre"],
    wind: ["abrite", "modere"],
    space: ["moyen", "grand"],
    goals: ["fleurs", "facile"],
    potLiters: 6,
    waterNeed: 3,
    compostNeed: 1,
    difficulty: "Facile",
    harvest: "Fleurs comestibles et décoratives",
    tags: ["Fleur", "Comestible", "Balcon"],
    description: "Une fleur facile et généreuse qui apporte vite de la couleur sur balcon.",
    tips: ["Évitez les pots trop riches en engrais", "Palissez légèrement si elle s'allonge"]
  },
  {
    name: "Persil",
    exposure: ["mi-ombre", "ombre"],
    wind: ["abrite", "modere", "fort"],
    space: ["petit", "moyen", "grand"],
    goals: ["aromatiques", "facile"],
    potLiters: 4,
    waterNeed: 3,
    compostNeed: 2,
    difficulty: "Facile",
    harvest: "Feuilles coupées régulièrement",
    tags: ["Aromatique", "Compact", "Débutant"],
    description: "Une bonne option pour les petits espaces et les expositions douces.",
    tips: ["Achetez un plant déjà formé", "Coupez les tiges extérieures en priorité"]
  },
  {
    name: "Géranium",
    exposure: ["soleil", "mi-ombre"],
    wind: ["abrite", "modere", "fort"],
    space: ["petit", "moyen", "grand"],
    goals: ["fleurs", "facile"],
    potLiters: 5,
    waterNeed: 2,
    compostNeed: 2,
    difficulty: "Facile",
    harvest: "Floraison longue",
    tags: ["Fleur", "Robuste", "Balcon"],
    description: "Une plante classique de balcon, florifère et assez tolérante.",
    tips: ["Retirez les fleurs fanées", "Arrosez plus souvent pendant les fortes chaleurs"]
  },
  {
    name: "Pétunia",
    exposure: ["soleil"],
    wind: ["abrite", "modere"],
    space: ["petit", "moyen", "grand"],
    goals: ["fleurs"],
    potLiters: 5,
    waterNeed: 3,
    compostNeed: 3,
    difficulty: "Facile",
    harvest: "Floraison généreuse",
    tags: ["Fleur", "Florifère", "Suspension"],
    description: "Parfait pour donner rapidement un effet coloré et abondant.",
    tips: ["Supprimez les fleurs fanées", "Nourrissez un peu en période de floraison"]
  },
  {
    name: "Bégonia",
    exposure: ["mi-ombre", "ombre"],
    wind: ["abrite", "modere"],
    space: ["petit", "moyen", "grand"],
    goals: ["fleurs", "facile"],
    potLiters: 4,
    waterNeed: 3,
    compostNeed: 2,
    difficulty: "Facile",
    harvest: "Couleur en zone peu ensoleillée",
    tags: ["Fleur", "Ombre", "Décoratif"],
    description: "Très utile pour fleurir un balcon lumineux mais sans soleil brûlant.",
    tips: ["Évitez l'eau stagnante", "Placez-le à l'abri du soleil de midi"]
  },
  {
    name: "Ciboulette",
    exposure: ["soleil", "mi-ombre"],
    wind: ["abrite", "modere", "fort"],
    space: ["petit", "moyen", "grand"],
    goals: ["aromatiques", "facile"],
    potLiters: 3,
    waterNeed: 2,
    compostNeed: 1,
    difficulty: "Très facile",
    harvest: "Tiges fraîches à couper souvent",
    tags: ["Aromatique", "Simple", "Compacte"],
    description: "Une des aromatiques les plus faciles à garder en pot.",
    tips: ["Coupez régulièrement", "Divisez la touffe si elle grossit"]
  },
  {
    name: "Romarin",
    exposure: ["soleil"],
    wind: ["abrite", "modere", "fort"],
    space: ["moyen", "grand"],
    goals: ["aromatiques", "facile"],
    potLiters: 10,
    waterNeed: 1,
    compostNeed: 1,
    difficulty: "Facile",
    harvest: "Tiges parfumées toute l'année",
    tags: ["Aromatique", "Méditerranéenne", "Robuste"],
    description: "Parfait pour les balcons ensoleillés si le pot est assez profond et drainant.",
    tips: ["Placez-le dans un substrat léger", "Évitez les arrosages trop fréquents"]
  },
  {
    name: "Origan",
    exposure: ["soleil", "mi-ombre"],
    wind: ["abrite", "modere", "fort"],
    space: ["petit", "moyen", "grand"],
    goals: ["aromatiques", "facile"],
    potLiters: 4,
    waterNeed: 1,
    compostNeed: 1,
    difficulty: "Facile",
    harvest: "Feuilles parfumées pour cuisine",
    tags: ["Aromatique", "Compact", "Cuisine"],
    description: "Une aromatique simple qui pousse bien en jardinière ou en petit pot.",
    tips: ["Pincez pour densifier", "Laissez sécher la surface entre deux arrosages"]
  },
  {
    name: "Sauge",
    exposure: ["soleil"],
    wind: ["abrite", "modere", "fort"],
    space: ["moyen", "grand"],
    goals: ["aromatiques", "facile"],
    potLiters: 7,
    waterNeed: 1,
    compostNeed: 1,
    difficulty: "Facile",
    harvest: "Feuilles aromatiques durables",
    tags: ["Aromatique", "Soleil", "Durable"],
    description: "Une plante parfumée, robuste et adaptée aux expositions chaudes.",
    tips: ["Évitez l'excès d'eau", "Taillez au printemps pour garder une forme compacte"]
  },
  {
    name: "Coriandre",
    exposure: ["soleil", "mi-ombre"],
    wind: ["abrite", "modere"],
    space: ["petit", "moyen", "grand"],
    goals: ["aromatiques"],
    potLiters: 4,
    waterNeed: 3,
    compostNeed: 1,
    difficulty: "Moyen",
    harvest: "Feuilles jeunes hors chaleur forte",
    tags: ["Aromatique", "Fraîche", "Cuisine"],
    description: "Intéressante pour les balcons doux, surtout hors grosse chaleur.",
    tips: ["Semez en petites quantités", "Gardez le terreau frais sans l'alourdir"]
  },
  {
    name: "Épinard",
    exposure: ["mi-ombre", "soleil"],
    wind: ["abrite", "modere"],
    space: ["petit", "moyen", "grand"],
    goals: ["legumes", "facile"],
    potLiters: 4,
    waterNeed: 3,
    compostNeed: 2,
    difficulty: "Facile",
    harvest: "Feuilles au printemps et en automne",
    tags: ["Légume", "Feuilles", "Mi-ombre"],
    description: "Très utile pour les balcons peu brûlants, surtout au printemps et en automne.",
    tips: ["Semez dans un terreau frais", "Récoltez les feuilles au fur et à mesure"]
  },
  {
    name: "Roquette",
    exposure: ["soleil", "mi-ombre"],
    wind: ["abrite", "modere", "fort"],
    space: ["petit", "moyen", "grand"],
    goals: ["legumes", "facile"],
    potLiters: 3,
    waterNeed: 3,
    compostNeed: 1,
    difficulty: "Très facile",
    harvest: "Jeunes feuilles rapides",
    tags: ["Légume", "Rapide", "Coupe"],
    description: "Une culture pratique pour récolter vite sans prendre beaucoup de place.",
    tips: ["Semez peu mais souvent", "Récoltez jeune pour garder des feuilles tendres"]
  },
  {
    name: "Haricot nain",
    exposure: ["soleil"],
    wind: ["abrite", "modere"],
    space: ["moyen", "grand"],
    goals: ["legumes"],
    potLiters: 8,
    waterNeed: 4,
    compostNeed: 2,
    difficulty: "Facile",
    harvest: "Gousses en été",
    tags: ["Légume", "Été", "Productif"],
    description: "Une option intéressante pour produire sans avoir besoin d'une grande hauteur.",
    tips: ["Semez quand les températures sont douces", "Arrosez pendant la floraison"]
  },
  {
    name: "Pois nain",
    exposure: ["soleil", "mi-ombre"],
    wind: ["abrite", "modere"],
    space: ["moyen", "grand"],
    goals: ["legumes", "facile"],
    potLiters: 6,
    waterNeed: 3,
    compostNeed: 1,
    difficulty: "Facile",
    harvest: "Gousses de printemps",
    tags: ["Légume", "Printemps", "Accessible"],
    description: "Adapté aux balcons frais de début de saison, avec un petit support si besoin.",
    tips: ["Semez tôt dans la saison", "Aidez les tiges à grimper si nécessaire"]
  },
  {
    name: "Blette",
    exposure: ["soleil", "mi-ombre"],
    wind: ["abrite", "modere", "fort"],
    space: ["moyen", "grand"],
    goals: ["legumes", "facile"],
    potLiters: 10,
    waterNeed: 3,
    compostNeed: 3,
    difficulty: "Facile",
    harvest: "Feuilles sur une longue période",
    tags: ["Légume", "Feuillage", "Longue récolte"],
    description: "Une plante généreuse qui tient bien en bac et permet des récoltes prolongées.",
    tips: ["Coupez les grandes feuilles extérieures", "Gardez un pot assez profond"]
  },
  {
    name: "Souci",
    exposure: ["soleil", "mi-ombre"],
    wind: ["abrite", "modere", "fort"],
    space: ["petit", "moyen", "grand"],
    goals: ["fleurs", "facile"],
    potLiters: 3,
    waterNeed: 2,
    compostNeed: 1,
    difficulty: "Très facile",
    harvest: "Fleurs mellifères",
    tags: ["Fleur", "Rustique", "Mellifère"],
    description: "Une fleur simple à vivre, pratique pour un balcon fleuri et tolérant.",
    tips: ["Retirez les fleurs fanées", "Semez facilement au printemps"]
  },
  {
    name: "Impatiens",
    exposure: ["mi-ombre", "ombre"],
    wind: ["abrite", "modere"],
    space: ["petit", "moyen", "grand"],
    goals: ["fleurs", "facile"],
    potLiters: 4,
    waterNeed: 4,
    compostNeed: 2,
    difficulty: "Facile",
    harvest: "Couleur en balcon ombragé",
    tags: ["Fleur", "Ombre", "Très simple"],
    description: "Une valeur sûre pour donner vite de la couleur sur un balcon peu ensoleillé.",
    tips: ["Gardez le terreau frais", "Supprimez les tiges abîmées"]
  },
  {
    name: "Fuchsia",
    exposure: ["mi-ombre", "ombre"],
    wind: ["abrite", "modere"],
    space: ["petit", "moyen", "grand"],
    goals: ["fleurs"],
    potLiters: 5,
    waterNeed: 4,
    compostNeed: 2,
    difficulty: "Moyen",
    harvest: "Floraison retombante",
    tags: ["Fleur", "Ombre", "Retombant"],
    description: "Très décoratif en suspension ou en pot, surtout sans soleil fort.",
    tips: ["Évitez les expositions très chaudes", "Arrosez dès que le mélange sèche en surface"]
  }
];


